/*
 * objects.h - Object dictionary
 *
 * Copyright (C) 1998-2018  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.20.0
 * from project /home/tiens/Workspace/cumulocity/private-agents-linux/canopen/m1.can
 * on 2018/11/19 at 21:09:02.
 */

/**
 * \file objects.h
 * \author port GmbH
 *
 * This module contains the object dictionary
 * of the CANopen device.
 */


#ifndef OBJECTS_H
# define OBJECTS_H	1



/* Declaration of Variables (Maintenance) */

extern CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR UNSIGNED32 p301_device_type;
extern CO_DT_INIT_VAR UNSIGNED8 p301_error_register;
extern CO_DT_INIT_VAR UNSIGNED32 p301_manu_status_register;
extern CO_DT_INIT_VAR UNSIGNED32 p301_pre_defined_error_field[2];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_device_name[11];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_hardware_version[4];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_software_version[4];
extern CO_DT_INIT_VAR UNSIGNED32 p301_cob_id_emcy;
extern CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time;
extern CO_DT_INIT_VAR IDENTITY_T p301_identity;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n1_ssdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n1_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n2_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n3_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n4_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n5_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n6_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n7_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n8_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n9_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n10_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n11_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n12_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n13_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n14_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n15_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n16_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n17_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n18_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n19_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n20_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n21_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n22_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n23_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n24_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n25_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n26_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n27_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n28_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n29_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n30_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n31_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n32_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n33_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n34_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n35_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n36_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n37_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n38_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n39_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n40_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n41_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n42_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n43_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n44_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n45_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n46_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n47_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n48_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n49_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n50_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n51_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n52_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n53_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n54_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n55_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n56_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n57_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n58_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n59_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n60_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n61_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n62_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n63_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n64_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n65_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n66_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n67_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n68_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n69_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n70_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n71_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n72_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n73_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n74_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n75_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n76_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n77_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n78_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n79_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n80_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n81_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n82_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n83_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n84_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n85_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n86_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n87_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n88_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n89_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n90_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n91_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n92_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n93_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n94_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n95_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n96_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n97_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n98_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n99_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n100_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n101_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n102_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n103_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n104_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n105_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n106_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n107_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n108_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n109_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n110_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n111_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n112_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n113_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n114_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n115_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n116_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n117_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n118_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n119_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n120_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n121_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n122_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n123_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n124_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n125_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n126_csdo_par;
extern CO_DT_INIT_VAR SDO_COMM_PAR_T p301_n127_csdo_par;
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */


/* Declaration of Value Descriptions */

#ifdef CONFIG_EXTERN_VALUE_DESCRIPTION
extern VALUE_DESC_T CO_CONST i1000_desc[1];
extern VALUE_DESC_T CO_CONST i1001_desc[1];
extern VALUE_DESC_T CO_CONST i1002_desc[1];
extern VALUE_DESC_T CO_CONST i1003_desc[2];
extern VALUE_DESC_T CO_CONST i1008_desc[1];
extern VALUE_DESC_T CO_CONST i1009_desc[1];
extern VALUE_DESC_T CO_CONST i100A_desc[1];
extern VALUE_DESC_T CO_CONST i1014_desc[1];
extern VALUE_DESC_T CO_CONST i1017_desc[1];
extern VALUE_DESC_T CO_CONST i1018_desc[5];
extern VALUE_DESC_T CO_CONST i1200_desc[3];
extern VALUE_DESC_T CO_CONST i1280_desc[4];
extern VALUE_DESC_T CO_CONST i1281_desc[4];
extern VALUE_DESC_T CO_CONST i1282_desc[4];
extern VALUE_DESC_T CO_CONST i1283_desc[4];
extern VALUE_DESC_T CO_CONST i1284_desc[4];
extern VALUE_DESC_T CO_CONST i1285_desc[4];
extern VALUE_DESC_T CO_CONST i1286_desc[4];
extern VALUE_DESC_T CO_CONST i1287_desc[4];
extern VALUE_DESC_T CO_CONST i1288_desc[4];
extern VALUE_DESC_T CO_CONST i1289_desc[4];
extern VALUE_DESC_T CO_CONST i128A_desc[4];
extern VALUE_DESC_T CO_CONST i128B_desc[4];
extern VALUE_DESC_T CO_CONST i128C_desc[4];
extern VALUE_DESC_T CO_CONST i128D_desc[4];
extern VALUE_DESC_T CO_CONST i128E_desc[4];
extern VALUE_DESC_T CO_CONST i128F_desc[4];
extern VALUE_DESC_T CO_CONST i1290_desc[4];
extern VALUE_DESC_T CO_CONST i1291_desc[4];
extern VALUE_DESC_T CO_CONST i1292_desc[4];
extern VALUE_DESC_T CO_CONST i1293_desc[4];
extern VALUE_DESC_T CO_CONST i1294_desc[4];
extern VALUE_DESC_T CO_CONST i1295_desc[4];
extern VALUE_DESC_T CO_CONST i1296_desc[4];
extern VALUE_DESC_T CO_CONST i1297_desc[4];
extern VALUE_DESC_T CO_CONST i1298_desc[4];
extern VALUE_DESC_T CO_CONST i1299_desc[4];
extern VALUE_DESC_T CO_CONST i129A_desc[4];
extern VALUE_DESC_T CO_CONST i129B_desc[4];
extern VALUE_DESC_T CO_CONST i129C_desc[4];
extern VALUE_DESC_T CO_CONST i129D_desc[4];
extern VALUE_DESC_T CO_CONST i129E_desc[4];
extern VALUE_DESC_T CO_CONST i129F_desc[4];
extern VALUE_DESC_T CO_CONST i12A0_desc[4];
extern VALUE_DESC_T CO_CONST i12A1_desc[4];
extern VALUE_DESC_T CO_CONST i12A2_desc[4];
extern VALUE_DESC_T CO_CONST i12A3_desc[4];
extern VALUE_DESC_T CO_CONST i12A4_desc[4];
extern VALUE_DESC_T CO_CONST i12A5_desc[4];
extern VALUE_DESC_T CO_CONST i12A6_desc[4];
extern VALUE_DESC_T CO_CONST i12A7_desc[4];
extern VALUE_DESC_T CO_CONST i12A8_desc[4];
extern VALUE_DESC_T CO_CONST i12A9_desc[4];
extern VALUE_DESC_T CO_CONST i12AA_desc[4];
extern VALUE_DESC_T CO_CONST i12AB_desc[4];
extern VALUE_DESC_T CO_CONST i12AC_desc[4];
extern VALUE_DESC_T CO_CONST i12AD_desc[4];
extern VALUE_DESC_T CO_CONST i12AE_desc[4];
extern VALUE_DESC_T CO_CONST i12AF_desc[4];
extern VALUE_DESC_T CO_CONST i12B0_desc[4];
extern VALUE_DESC_T CO_CONST i12B1_desc[4];
extern VALUE_DESC_T CO_CONST i12B2_desc[4];
extern VALUE_DESC_T CO_CONST i12B3_desc[4];
extern VALUE_DESC_T CO_CONST i12B4_desc[4];
extern VALUE_DESC_T CO_CONST i12B5_desc[4];
extern VALUE_DESC_T CO_CONST i12B6_desc[4];
extern VALUE_DESC_T CO_CONST i12B7_desc[4];
extern VALUE_DESC_T CO_CONST i12B8_desc[4];
extern VALUE_DESC_T CO_CONST i12B9_desc[4];
extern VALUE_DESC_T CO_CONST i12BA_desc[4];
extern VALUE_DESC_T CO_CONST i12BB_desc[4];
extern VALUE_DESC_T CO_CONST i12BC_desc[4];
extern VALUE_DESC_T CO_CONST i12BD_desc[4];
extern VALUE_DESC_T CO_CONST i12BE_desc[4];
extern VALUE_DESC_T CO_CONST i12BF_desc[4];
extern VALUE_DESC_T CO_CONST i12C0_desc[4];
extern VALUE_DESC_T CO_CONST i12C1_desc[4];
extern VALUE_DESC_T CO_CONST i12C2_desc[4];
extern VALUE_DESC_T CO_CONST i12C3_desc[4];
extern VALUE_DESC_T CO_CONST i12C4_desc[4];
extern VALUE_DESC_T CO_CONST i12C5_desc[4];
extern VALUE_DESC_T CO_CONST i12C6_desc[4];
extern VALUE_DESC_T CO_CONST i12C7_desc[4];
extern VALUE_DESC_T CO_CONST i12C8_desc[4];
extern VALUE_DESC_T CO_CONST i12C9_desc[4];
extern VALUE_DESC_T CO_CONST i12CA_desc[4];
extern VALUE_DESC_T CO_CONST i12CB_desc[4];
extern VALUE_DESC_T CO_CONST i12CC_desc[4];
extern VALUE_DESC_T CO_CONST i12CD_desc[4];
extern VALUE_DESC_T CO_CONST i12CE_desc[4];
extern VALUE_DESC_T CO_CONST i12CF_desc[4];
extern VALUE_DESC_T CO_CONST i12D0_desc[4];
extern VALUE_DESC_T CO_CONST i12D1_desc[4];
extern VALUE_DESC_T CO_CONST i12D2_desc[4];
extern VALUE_DESC_T CO_CONST i12D3_desc[4];
extern VALUE_DESC_T CO_CONST i12D4_desc[4];
extern VALUE_DESC_T CO_CONST i12D5_desc[4];
extern VALUE_DESC_T CO_CONST i12D6_desc[4];
extern VALUE_DESC_T CO_CONST i12D7_desc[4];
extern VALUE_DESC_T CO_CONST i12D8_desc[4];
extern VALUE_DESC_T CO_CONST i12D9_desc[4];
extern VALUE_DESC_T CO_CONST i12DA_desc[4];
extern VALUE_DESC_T CO_CONST i12DB_desc[4];
extern VALUE_DESC_T CO_CONST i12DC_desc[4];
extern VALUE_DESC_T CO_CONST i12DD_desc[4];
extern VALUE_DESC_T CO_CONST i12DE_desc[4];
extern VALUE_DESC_T CO_CONST i12DF_desc[4];
extern VALUE_DESC_T CO_CONST i12E0_desc[4];
extern VALUE_DESC_T CO_CONST i12E1_desc[4];
extern VALUE_DESC_T CO_CONST i12E2_desc[4];
extern VALUE_DESC_T CO_CONST i12E3_desc[4];
extern VALUE_DESC_T CO_CONST i12E4_desc[4];
extern VALUE_DESC_T CO_CONST i12E5_desc[4];
extern VALUE_DESC_T CO_CONST i12E6_desc[4];
extern VALUE_DESC_T CO_CONST i12E7_desc[4];
extern VALUE_DESC_T CO_CONST i12E8_desc[4];
extern VALUE_DESC_T CO_CONST i12E9_desc[4];
extern VALUE_DESC_T CO_CONST i12EA_desc[4];
extern VALUE_DESC_T CO_CONST i12EB_desc[4];
extern VALUE_DESC_T CO_CONST i12EC_desc[4];
extern VALUE_DESC_T CO_CONST i12ED_desc[4];
extern VALUE_DESC_T CO_CONST i12EE_desc[4];
extern VALUE_DESC_T CO_CONST i12EF_desc[4];
extern VALUE_DESC_T CO_CONST i12F0_desc[4];
extern VALUE_DESC_T CO_CONST i12F1_desc[4];
extern VALUE_DESC_T CO_CONST i12F2_desc[4];
extern VALUE_DESC_T CO_CONST i12F3_desc[4];
extern VALUE_DESC_T CO_CONST i12F4_desc[4];
extern VALUE_DESC_T CO_CONST i12F5_desc[4];
extern VALUE_DESC_T CO_CONST i12F6_desc[4];
extern VALUE_DESC_T CO_CONST i12F7_desc[4];
extern VALUE_DESC_T CO_CONST i12F8_desc[4];
extern VALUE_DESC_T CO_CONST i12F9_desc[4];
extern VALUE_DESC_T CO_CONST i12FA_desc[4];
extern VALUE_DESC_T CO_CONST i12FB_desc[4];
extern VALUE_DESC_T CO_CONST i12FC_desc[4];
extern VALUE_DESC_T CO_CONST i12FD_desc[4];
extern VALUE_DESC_T CO_CONST i12FE_desc[4];
#endif /* CONFIG_EXTERN_VALUE_DESCRIPTION */

/* Declaration of Object Dictionary */
#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR OBJDIR_T objDir[];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
#endif /* OBJECTS_H*/


/*----------------------------------------------------------------------------*/

