/*
 * objects.h - Object dictionary
 *
 * Copyright (C) 1998-2018  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.20.0
 * from project /home/tiens/Workspace/Port-CANOpen/canopen_simulator/cdt.can
 * on 2018/09/18 at 12:30:53.
 */

/**
 * \file objects.h
 * \author port GmbH
 *
 * This module contains the object dictionary
 * of the CANopen device.
 */


#ifndef OBJECTS_H
# define OBJECTS_H	1



/* Declaration of Variables (Maintenance) */

extern CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR UNSIGNED32 p301_device_type;
extern CO_DT_INIT_VAR UNSIGNED8 p301_error_register;
extern CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time;
extern CO_DT_INIT_VAR IDENTITY_T p301_identity;
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
extern CO_DT_INIT_VAR REAL32 p2001_real;
extern CO_DT_INIT_VAR UNSIGNED8 p2002;
extern CO_DT_INIT_VAR INTEGER16 p6000[3];
extern CO_DT_INIT_VAR UNSIGNED64 p6001;


/* Declaration of Value Descriptions */

#ifdef CONFIG_EXTERN_VALUE_DESCRIPTION
extern VALUE_DESC_T CO_CONST p301_device_type_desc[1];
extern VALUE_DESC_T CO_CONST p301_error_register_desc[1];
extern VALUE_DESC_T CO_CONST p301_prod_hb_time_desc[1];
extern VALUE_DESC_T CO_CONST p301_identity_desc[5];
extern VALUE_DESC_T CO_CONST p2001_real_desc[1];
extern VALUE_DESC_T CO_CONST p2002_desc[1];
extern VALUE_DESC_T CO_CONST p6000_desc[3];
extern VALUE_DESC_T CO_CONST p6001_desc[1];
#endif /* CONFIG_EXTERN_VALUE_DESCRIPTION */

/* Declaration of Object Dictionary */
#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern OBJDIR_T objDir[];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
#endif /* OBJECTS_H*/


/*----------------------------------------------------------------------------*/

