/*
 * objects.c - Object dictionary
 *
 * Copyright (C) 1998-2018  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the CANopen Design Tool V2.3.20.0
 * from project /home/tiens/Workspace/Port-CANOpen/canopen_simulator/cdt.can
 * on 2018/09/18 at 12:30:53.
 */

/**
 * \file objects.c
 * \author port GmbH
 *
 * This module contains the object dictionary
 * of the CANopen device.
 */


#define OBJECTS_C 1
#include <stdlib.h>
#include <cal_conf.h>      /* !!! first file to include for all CANopen */
#include <co_acces.h>
#include <co_pdo.h>
#include <co_sdo.h>
#include <co_stru.h>
#include <objects.h>
/*  number of entries in the object dictionary */
CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements = 8;

/*  Definition of Variables (Device Objects)  */
CO_DT_INIT_VAR UNSIGNED32 p301_device_type = { 0x0000000UL };
CO_DT_INIT_VAR UNSIGNED8 p301_error_register = { 0x00 };
CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time = { 0x00000000 };
CO_DT_INIT_VAR IDENTITY_T p301_identity = { 0x4, 0x0UL, 0x0UL, 0x0UL,
    0x0UL };
CO_DT_INIT_VAR REAL32 p2001_real = { 23.4559993744 };
CO_DT_INIT_VAR UNSIGNED8 p2002 = { 0x81 };
CO_DT_INIT_VAR INTEGER16 p6000[3] = { 0x2, 0xFFFF, 0x8000};
CO_DT_INIT_VAR UNSIGNED64 p6001 = SET_U64(0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00);



/* Default values */
CO_CONST REAL32 l0_default1_0008[1] = { 23.4559993744 };
CO_CONST UNSIGNED64 l0_default1_001B[1] = { SET_U64(0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00) };
CO_CONST UNSIGNED8 l0_default1_0005[3] = { 0x0, 0x4, 0x81 };
CO_CONST UNSIGNED16 l0_default1_0006[1] = { 0x0 };
CO_CONST INTEGER16 l0_default1_0003[3] = { 0x2, 0xffff, 0x8000 };
CO_CONST UNSIGNED32 l0_default1_0007[1] = { 0x0UL };

/* Limits */
#ifdef CONFIG_LIMITS_CHECK
CO_CONST LIMIT_I16_T l0_limits1_0003[2] = { {0x1, 0xfe}, {0x8000,
    0x7fff} };
CO_CONST LIMIT_U8_T l0_limits1_0005[2] = { {0x0, 0xff}, {0x1, 0x4} };
CO_CONST LIMIT_U16_T l0_limits1_0006[1] = { {0x0, 0xffff} };
CO_CONST LIMIT_U32_T l0_limits1_0007[1] = { {0x0UL, 0xffffffffUL} };
CO_CONST LIMIT_R32_T l0_limits1_0008[1] = { {-3.40282346639e+38,
    3.40282346639e+38} };
CO_CONST LIMIT_U64_T l0_limits1_001B[1] = { {SET_U64(0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00), SET_U64(0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff)} };
#endif /* CONFIG_LIMITS_CHECK */


/*  Definition of Value Descriptions  */
VALUE_DESC_T CO_CONST  p301_device_type_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_CONST_PERM | CO_READ_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p301_error_register_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0005[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p301_prod_hb_time_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0006[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p301_identity_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0005[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p2001_real_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0008[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0008[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_REAL32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p2002_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_0005[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p6000_desc[3] = {
    { (UNSIGNED8 *)&l0_default1_0003[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0003[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_INTEGER16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0003[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0003[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_INTEGER16, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0003[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0003[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_INTEGER16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };
VALUE_DESC_T CO_CONST  p6001_desc[1] =  {
    { (UNSIGNED8 *) &l0_default1_001B[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_001B[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED64, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };

/* Definition of the object directory */
OBJDIR_T objDir[] = {
{   (UNSIGNED8 *)&p301_device_type,
    (VALUE_DESC_T *)p301_device_type_desc,
    0x1000, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p301_error_register,
    (VALUE_DESC_T *)p301_error_register_desc,
    0x1001, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p301_prod_hb_time,
    (VALUE_DESC_T *)p301_prod_hb_time_desc,
    0x1017, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p301_identity,
    (VALUE_DESC_T *)p301_identity_desc,
    0x1018, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p2001_real,
    (VALUE_DESC_T *)p2001_real_desc,
    0x2001, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p2002,
    (VALUE_DESC_T *)p2002_desc,
    0x2002, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)p6000,
    (VALUE_DESC_T *)p6000_desc,
    0x6000, 3 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },
{   (UNSIGNED8 *)&p6001,
    (VALUE_DESC_T *)p6001_desc,
    0x6001, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    }
};
